language: node_js
node_js:
  - '12'

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - export TZ=Europe/Berlin

before_script:
  - export NODE_ICU_DATA=node_modules/full-icu

script:
  - yarn test
